name: Swift Reveal

on:
  pull_request:
    branches:
      - '*'

jobs:
  swiftReveal:
    name: Swift Reveal
    runs-on: macos-latest
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - name: Cache Gradle Caches
        uses: gradle/gradle-build-action@v2
      - name: Run Gradle tasks
        run: ./gradlew :example:swiftReveal
      - run: ls build/sourcekitten-0.34.1-src/.build
        if: always()

      # TODO: publish comment in pull request
      - name: Publish Swift Reveal to Summary
        id: build_swift_reveal_comment
        run: |
          echo '```swift' >> $GITHUB_OUTPUT
          cat example/swift-reveal/module.swift >> $GITHUB_OUTPUT
          echo $'\n' >> $GITHUB_OUTPUT
          echo '```' >> $GITHUB_OUTPUT
        if: success()
      - name: maintain-comment
        uses: actions-cool/maintain-one-comment@v3

        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ${{join(steps.build_swift_reveal_comment.outputs.*, '\n')}}
          body-include: '<!-- Created by actions-cool/maintain-one-comment -->'

