name: Swift Reveal

on:
  pull_request:
    branches:
      - '*'

jobs:
  swiftReveal:
    name: Swift Reveal
    runs-on: macos-latest
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - name: Cache Gradle Caches
        uses: gradle/gradle-build-action@v2
      - name: Run Gradle tasks
        run: ./gradlew :example:swiftReveal

      - name: Publish Swift Reveal to Summary
        id: build_swift_reveal_comment
        run: |
          FILE_CONTENT=$(cat example/swift-reveal/module.swift)
          echo "::set-output name=content::$FILE_CONTENT"
        if: success()
      - name: maintain-comment
        uses: actions-cool/maintain-one-comment@v3
        if: success()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ${{ steps.build_swift_reveal_comment.outputs.content }}
          body-include: '<!-- Created by actions-cool/maintain-one-comment -->'

